baseURL = "https://keptn.netlify.com/"
languageCode = "en-us"
title = "keptn"
theme = "hugo-serif-theme"

[params]
    google_analytics_id=""

[[menu.main]]
    name = "Roadmap"
    url = "/services/"
    weight = 1
