baseURL = "https://keptn.sh/"
languageCode = "en-us"
title = "keptn"
theme = "hugo-serif-theme"

[params]
    google_analytics_id="UA-133584243-1"

[blackfriday]
    plainIDAnchors = true
    hrefTargetBlank = false
    angledQuotes = false
    latexDashes = true
    extensions = [""]