baseURL = "https://hugoserif.netlify.com/"
languageCode = "en-us"
title = "keptn"
theme = "hugo-serif-theme"

[params]
    google_analytics_id=""

[[menu.main]]
	name = "Github"
	url = "https://github.com/keptn/keptn.github.io"
    weight = 1

[[menu.main]]
    name = "Roadmap"
    url = "/roadmap/"
    weight = 2